# Generated by roxygen2: do not edit by hand

#' Check CUDA Availability
#'
#' Checks if CUDA is available and initializes the specified device.
#' If already initialized for the device, it returns success without re-initializing.
#'
#' @param device_id Integer CUDA device ID (default: 0).
#' @return A list with components:
#'   \describe{
#'     \item{status}{Integer status code (0 = success, negative = error).}
#'     \item{message}{Character description of the status.}
#'     \item{available}{Logical indicating if CUDA initialization was successful.}
#'   }
#' @examples
#' \dontrun{
#' cuda_info <- check_cuda_available()
#' if (cuda_info$available) {
#'   print("CUDA is ready!")
#' } else {
#'   print(paste("CUDA Error:", cuda_info$message))
#' }
#' }
#' @export
#' @useDynLib RidgeCuda, .registration = TRUE
check_cuda_available <- function(device_id = 0) {
  # Ensure device_id is a single integer
  if (!is.numeric(device_id) || length(device_id) != 1 || device_id < 0 || floor(device_id) != device_id) {
    stop("device_id must be a single non-negative integer.")
  }
  device_id <- as.integer(device_id)

  # Call the C++ interface function registered as "check_cuda_available_r"
  result <- .Call("check_cuda_available_r", device_id, PACKAGE = "RidgeCuda")

  # Add a simple boolean flag for convenience
  result$available <- (result$status == 0)

  return(result)
}
